apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: odoo-staging-db
  namespace: odoo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: odoo-staging-db
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: odoo/staging
        property: DB_HOST
    - secretKey: DB_USER
      remoteRef:
        key: odoo/staging
        property: STAGING_DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: odoo/staging
        property: STAGING_DB_PASSWORD
