apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: odoo-db
  namespace: odoo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: odoo-db
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: odoo/prod
        property: DB_HOST
    - secretKey: DB_USER
      remoteRef:
        key: odoo/prod
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: odoo/prod
        property: DB_PASSWORD
